goleveldb bloom filter
cosmos/cosmos-db pull request #3
Opened 2022-08-15 21:44 UTC by marbar3778

2022-08-16 19:25 UTC, alexanderbez approved these changes
utACK. Is there a reason as to why 10 was chosen for the bloom filter? Also, is that the number of hashes or bit/buckets?

2022-08-18 12:28 UTC, faddat commented
heh, @alexanderbez -- in fact I haven't reallhy been able to get into the logic of why on those configs.  Not sure that Marko has been able to either?

I figure the next step here is to use the iavl benchmarks that we used to test and mature pebble here, as well, so that we can get some performance information.

2022-08-22 10:08 UTC, faddat approved these changes

2022-08-22 11:12 UTC, faddat requested changes
something is wrong with the bloom filter config here...

2022-08-25 14:22 UTC, closed without merging